from __future__ import annotations

import shutil
import subprocess  # nosec
from pathlib import Path


class SshError(RuntimeError):
    pass


def check_ssh_keygen() -> bool:
    return shutil.which("ssh-keygen") is not None


def get_ssh_version() -> str | None:
    if shutil.which("ssh") is None:
        return None
    # Fixed command, no user input.
    proc = subprocess.run(  # nosec
        ["ssh", "-V"], capture_output=True, text=True, check=False
    )
    return (proc.stderr or proc.stdout).strip() or None


def ssh_query_key_types() -> list[str] | None:
    if shutil.which("ssh") is None:
        return None
    # Fixed command, no user input.
    proc = subprocess.run(  # nosec
        ["ssh", "-Q", "key"], capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        return None
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def ssh_supports_key_type(key_type: str) -> bool | None:
    key_types = ssh_query_key_types()
    if key_types is None:
        return None
    return key_type in set(key_types)


def build_ssh_keygen_cmd(
    provider: str,
    key_path: Path,
    comment: str,
    passphrase: str | None,
    resident: bool,
    application: str | None,
    rounds: int,
) -> list[str]:
    if provider == "fido2":
        cmd = [
            "ssh-keygen",
            "-t",
            "ed25519-sk",
            "-f",
            str(key_path),
            "-C",
            comment,
        ]
        if resident:
            cmd.extend(["-O", "resident"])
        if application:
            cmd.extend(["-O", f"application={application}"])
        return cmd

    if provider == "software":
        cmd = [
            "ssh-keygen",
            "-t",
            "ed25519",
            "-a",
            str(rounds),
            "-f",
            str(key_path),
            "-C",
            comment,
            "-N",
            passphrase or "",
        ]
        return cmd

    raise ValueError(f"Unknown provider: {provider}")


def generate_key(cmd: list[str]) -> None:
    try:
        # Controlled command args generated by this tool.
        subprocess.run(cmd, check=True)  # nosec
    except subprocess.CalledProcessError as exc:
        raise SshError("ssh-keygen failed") from exc
