from __future__ import annotations

import shutil
import subprocess  # nosec
from pathlib import Path


class SshError(RuntimeError):
    pass


def check_ssh_keygen() -> bool:
    return shutil.which("ssh-keygen") is not None


def get_ssh_version() -> str | None:
    if shutil.which("ssh") is None:
        return None
    # Fixed command, no user input.
    proc = subprocess.run(  # nosec
        ["ssh", "-V"], capture_output=True, text=True, check=False
    )
    return (proc.stderr or proc.stdout).strip() or None


def build_ssh_keygen_cmd(
    provider: str,
    key_path: Path,
    comment: str,
    passphrase: str | None,
    resident: bool,
    application: str | None,
    rounds: int,
) -> list[str]:
    if provider == "fido2":
        cmd = [
            "ssh-keygen",
            "-t",
            "ed25519-sk",
            "-f",
            str(key_path),
            "-C",
            comment,
        ]
        if resident:
            cmd.extend(["-O", "resident"])
        if application:
            cmd.extend(["-O", f"application={application}"])
        return cmd

    if provider == "software":
        cmd = [
            "ssh-keygen",
            "-t",
            "ed25519",
            "-a",
            str(rounds),
            "-f",
            str(key_path),
            "-C",
            comment,
            "-N",
            passphrase or "",
        ]
        return cmd

    raise ValueError(f"Unknown provider: {provider}")


def generate_key(cmd: list[str]) -> None:
    try:
        # Controlled command args generated by this tool.
        subprocess.run(cmd, check=True)  # nosec
    except subprocess.CalledProcessError as exc:
        raise SshError("ssh-keygen failed") from exc
